"""
synthclinic.digital_twin.patient
-----------------------------
VirtualPatient — a multimodal synthetic patient combining all four
data modalities generated by GenMed generators.

This is the primary deliverable of the thesis project: a realistic
"virtual patient" that can be used to test and validate medical AI tools
without involving real patient data.

Usage
-----
    from synthclinic.digital_twin.patient import DigitalTwinFactory

    factory = DigitalTwinFactory(
        tabular_generator=tab_gen,
        ecg_generator=ecg_gen,
        clinical_generator=clinical_gen,
        mri_generator=mri_gen,
    )
    patient = factory.generate()
    patient.summary()
    patient.save("outputs/patient_001.json")
"""

from __future__ import annotations

import json
import logging
import uuid
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# VirtualPatient dataclass
# ---------------------------------------------------------------------------

@dataclass
class VirtualPatient:
    """
    Structured container for a single synthetic patient's multimodal data.

    Attributes
    ----------
    patient_id    : unique identifier (auto-generated UUID)
    demographics  : dict of tabular lab / demographic values
    ecg_segments  : list of ECG waveforms, each shape (T, 1)
    clinical_notes: list of synthetic clinical transcription strings
    mri_slices    : list of 2D MRI slices, each shape (1, H, W)
    metadata      : arbitrary dict for annotations (timestamp, generator versions, …)
    """
    patient_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    demographics: Dict[str, Any] = field(default_factory=dict)
    ecg_segments: List[np.ndarray] = field(default_factory=list)
    clinical_notes: List[str] = field(default_factory=list)
    mri_slices: List[np.ndarray] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Display
    # ------------------------------------------------------------------

    def summary(self) -> None:
        """Print a human-readable summary to stdout."""
        print(f"\n{'='*60}")
        print(f"  VirtualPatient  ID: {self.patient_id}")
        print(f"{'='*60}")
        print(f"  Demographics   : {len(self.demographics)} features")
        for k, v in list(self.demographics.items())[:6]:
            print(f"      {k:20s}: {v}")
        if len(self.demographics) > 6:
            print(f"      ... ({len(self.demographics) - 6} more)")
        print(f"  ECG segments   : {len(self.ecg_segments)} "
              f"(shape {self.ecg_segments[0].shape if self.ecg_segments else 'none'})")
        print(f"  Clinical notes : {len(self.clinical_notes)}")
        for note in self.clinical_notes[:1]:
            preview = note[:120].replace("\n", " ")
            print(f"      \"{preview}…\"")
        print(f"  MRI slices     : {len(self.mri_slices)} "
              f"(shape {self.mri_slices[0].shape if self.mri_slices else 'none'})")
        print(f"{'='*60}\n")

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def save(self, path: str | Path) -> None:
        """
        Serialise the patient to disk.

        Saves:
        - ``<path>/metadata.json``  : demographics, notes, metadata
        - ``<path>/ecg.npy``        : stacked ECG segments
        - ``<path>/mri.npy``        : stacked MRI slices
        """
        out_dir = Path(path)
        out_dir.mkdir(parents=True, exist_ok=True)

        meta = {
            "patient_id": self.patient_id,
            "demographics": {
                k: (v.item() if hasattr(v, "item") else v)
                for k, v in self.demographics.items()
            },
            "clinical_notes": self.clinical_notes,
            "metadata": self.metadata,
        }
        with open(out_dir / "metadata.json", "w") as f:
            json.dump(meta, f, indent=2)

        if self.ecg_segments:
            np.save(out_dir / "ecg.npy", np.stack(self.ecg_segments))
        if self.mri_slices:
            np.save(out_dir / "mri.npy", np.stack(self.mri_slices))

        logger.info("VirtualPatient %s saved to %s", self.patient_id, out_dir)

    @classmethod
    def load(cls, path: str | Path) -> "VirtualPatient":
        """Restore a VirtualPatient from disk."""
        in_dir = Path(path)
        with open(in_dir / "metadata.json") as f:
            meta = json.load(f)

        ecg = (
            [np.load(in_dir / "ecg.npy")[i] for i in range(len(np.load(in_dir / "ecg.npy")))]
            if (in_dir / "ecg.npy").exists()
            else []
        )
        mri = (
            [np.load(in_dir / "mri.npy")[i] for i in range(len(np.load(in_dir / "mri.npy")))]
            if (in_dir / "mri.npy").exists()
            else []
        )

        return cls(
            patient_id=meta["patient_id"],
            demographics=meta["demographics"],
            ecg_segments=ecg,
            clinical_notes=meta["clinical_notes"],
            mri_slices=mri,
            metadata=meta.get("metadata", {}),
        )


# ---------------------------------------------------------------------------
# DigitalTwinFactory
# ---------------------------------------------------------------------------

class DigitalTwinFactory:
    """
    Composes outputs from all four GenMed generators into VirtualPatient objects.

    All generators are optional — pass only the ones you have trained.

    Parameters
    ----------
    tabular_generator   : trained TabularGenerator (lab results / demographics)
    ecg_generator       : trained ECGGenerator
    clinical_generator  : trained ClinicalNotesGenerator
    mri_generator       : trained MRIGenerator
    n_ecg_segments      : ECG segments per patient (default 3)
    n_clinical_notes    : clinical notes per patient (default 1)
    n_mri_slices        : MRI slices per patient (default 5)
    clinical_prompt     : optional specialty prompt for clinical note generation
    """

    def __init__(
        self,
        tabular_generator=None,
        ecg_generator=None,
        clinical_generator=None,
        mri_generator=None,
        n_ecg_segments: int = 3,
        n_clinical_notes: int = 1,
        n_mri_slices: int = 5,
        clinical_prompt: Optional[str] = None,
    ) -> None:
        self._tab = tabular_generator
        self._ecg = ecg_generator
        self._clin = clinical_generator
        self._mri = mri_generator
        self.n_ecg = n_ecg_segments
        self.n_notes = n_clinical_notes
        self.n_mri = n_mri_slices
        self.clinical_prompt = clinical_prompt

    def generate(self, n_patients: int = 1) -> List[VirtualPatient]:
        """
        Generate *n_patients* complete virtual patients.

        Returns
        -------
        List of VirtualPatient objects.
        """
        patients = []
        for i in range(n_patients):
            patient = self._generate_one()
            patients.append(patient)
            logger.info("Generated virtual patient %d/%d  ID: %s",
                        i + 1, n_patients, patient.patient_id)
        return patients

    def _generate_one(self) -> VirtualPatient:
        demographics: Dict[str, Any] = {}
        ecg_segments: List[np.ndarray] = []
        clinical_notes: List[str] = []
        mri_slices: List[np.ndarray] = []

        # ── Tabular ───────────────────────────────────────────────────
        if self._tab is not None:
            df = self._tab.generate(1)
            demographics = df.iloc[0].to_dict()

        # ── ECG ───────────────────────────────────────────────────────
        if self._ecg is not None:
            segs = self._ecg.generate(self.n_ecg)  # (n, T, 1)
            ecg_segments = [segs[i] for i in range(len(segs))]

        # ── Clinical notes ────────────────────────────────────────────
        if self._clin is not None:
            notes = self._clin.generate(
                self.n_notes,
                prompt=self.clinical_prompt,
            )
            clinical_notes = notes

        # ── MRI ───────────────────────────────────────────────────────
        if self._mri is not None:
            slices = self._mri.generate(self.n_mri)  # (n, 1, H, W)
            mri_slices = [slices[i] for i in range(len(slices))]

        return VirtualPatient(
            demographics=demographics,
            ecg_segments=ecg_segments,
            clinical_notes=clinical_notes,
            mri_slices=mri_slices,
            metadata={
                "generators": {
                    "tabular": self._tab.__class__.__name__ if self._tab else None,
                    "ecg": self._ecg.__class__.__name__ if self._ecg else None,
                    "clinical": self._clin.__class__.__name__ if self._clin else None,
                    "mri": self._mri.__class__.__name__ if self._mri else None,
                }
            },
        )
